export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT= 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS';
export const FETCH_ALL_ORDERS_FAILED = 'FETCH_ALL_ORDERS_FAILED';
